"""create initial tables

Revision ID: 14b396195209
Revises: 
Create Date: 2026-01-01 20:05:03.310628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b396195209'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dvar_torah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rabbi_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_hebrew', sa.String(length=60), nullable=True),
    sa.Column('date_gregorian', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dvar_torah_date_gregorian'), 'dvar_torah', ['date_gregorian'], unique=False)
    op.create_table('pray_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_gregorian', sa.Date(), nullable=False),
    sa.Column('shacharit', sa.String(length=5), nullable=False),
    sa.Column('mincha', sa.String(length=5), nullable=False),
    sa.Column('arvit', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pray_times_date_gregorian'), 'pray_times', ['date_gregorian'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pray_times_date_gregorian'), table_name='pray_times')
    op.drop_table('pray_times')
    op.drop_index(op.f('ix_dvar_torah_date_gregorian'), table_name='dvar_torah')
    op.drop_table('dvar_torah')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
